public with sharing class ClassMathOperations {
    //Constructor
    public ClassMathOperations() {
    }   
    //Give a code for a method that adds two integers and returns the result
    public Integer addIntegers(Integer a, Integer b) {
        return a + b;
    }
    //Give a code for a method that subtracts two integers and returns the result
    public Integer subtractIntegers(Integer a, Integer b) {
        return a - b;
    }
    //Give a code for a method that multiplies two integers and returns the result
    public Integer multiplyIntegers(Integer a, Integer b) {
        return a * b;
    }
   
}